import Event from "./Events";

export const groups = [
  [{}, {}, {}, {}, {}], // empty to start

  // Thursday
  [{ event: Event.ecl, group: 1 }, { event: Event.esq, group: 1 }, {}, {}, {}],
  [{ event: Event.ecl, group: 2 }, { event: Event.esq, group: 2 }, {}, {}, {}],
  [{ event: Event.ecl, group: 3 }, { event: Event.esq, group: 3 }, {}, {}, {}],
  [
    { event: Event.ecl, group: 4 },
    { event: Event.esq, group: 4 },
    {},
    {},
    { event: Event.e3m, attempt: 1 },
  ],
  [
    { event: Event.esq, group: 5 },
    { event: Event.esq, group: 5 },
    {},
    {},
    { event: Event.e3m, attempt: 1 },
  ],
  [
    { event: Event.esq, group: 6 },
    { event: Event.esq, group: 6 },
    {},
    {},
    { event: Event.e3m, attempt: 1 },
  ],
  [{}, {}, {}, {}, {}], // lunch
  [
    { event: Event.e66, group: 1 },
    { event: Event.e66, group: 1 },
    { event: Event.e66, group: 1 },
    { event: Event.e66, group: 1 },
    {},
  ],
  [
    { event: Event.e66, group: 2 },
    { event: Event.e66, group: 2 },
    { event: Event.e66, group: 2 },
    { event: Event.e66, group: 2 },
    {},
  ],
  [
    { event: Event.e77, group: 1 },
    { event: Event.e77, group: 1 },
    { event: Event.e77, group: 1 },
    { event: Event.e77, group: 1 },
    {},
  ],
  [
    { event: Event.e77, group: 2 },
    { event: Event.e77, group: 2 },
    { event: Event.e77, group: 2 },
    { event: Event.e77, group: 2 },
    {},
  ],
  [
    { event: Event.eme, group: 1 },
    { event: Event.eme, group: 1 },
    { event: Event.eme, group: 1 },
    { event: Event.eme, group: 1 },
    {},
  ],
  [
    { event: Event.eme, group: 2 },
    { event: Event.eme, group: 2 },
    { event: Event.eme, group: 2 },
    { event: Event.eme, group: 2 },
    {},
  ],
  [
    { event: Event.ecl, round: "Final" },
    { event: Event.ecl, round: "Final" },
    { event: Event.eme, group: 3 },
    { event: Event.eme, group: 3 },
    {},
  ],
  [
    { event: Event.e3b, group: 1 },
    { event: Event.e3b, group: 1 },
    { event: Event.e3b, group: 1 },
    { event: Event.e3b, group: 1 },
    {},
  ],
  [
    { event: Event.e3b, group: 2 },
    { event: Event.e3b, group: 2 },
    { event: Event.e3b, group: 2 },
    { event: Event.e3b, group: 2 },
    {},
  ],
  [
    { event: Event.esq, round: 2 },
    { event: Event.esq, round: 2 },
    { event: Event.esq, round: 2 },
    { event: Event.esq, round: 2 },
    {},
  ],
  [{}, {}, {}, {}, {}], // dinner
  [{}, {}, {}, {}, { event: Event.e3f, attempt: 1 }],
  [{}, {}, {}, {}, {}], // empty to end day

  // Friday

  [{ event: Event.e44, group: 1 }, { event: Event.e44, group: 1 }, {}, {}, {}],
  [
    { event: Event.e44, group: 2 },
    { event: Event.e44, group: 2 },
    {},
    {},
    { event: Event.e3f, attempt: 1 },
  ],
  [
    { event: Event.e44, group: 3 },
    { event: Event.e44, group: 3 },
    {},
    {},
    { event: Event.e3f, attempt: 1 },
  ],
  [
    { event: Event.e44, group: 4 },
    { event: Event.e44, group: 4 },
    {},
    {},
    { event: Event.e3f, attempt: 1 },
  ],
  [
    { event: Event.e44, group: 5 },
    { event: Event.e44, group: 5 },
    { event: Event.e44, group: 1 },
    {},
    {},
  ],
  [
    { event: Event.e44, group: 6 },
    { event: Event.e44, group: 6 },
    { event: Event.e44, group: 2 },
    { event: Event.e44, group: 1 },
    {},
  ],

  [{}, {}, {}, {}, {}], // lunch

  [
    { event: Event.e55, group: 1 },
    { event: Event.e55, group: 1 },
    { event: Event.e55, group: 1 },
    { event: Event.e55, group: 1 },
    {},
  ],
  [
    { event: Event.e55, group: 2 },
    { event: Event.e55, group: 2 },
    { event: Event.e55, group: 2 },
    {},
    {},
  ],
  [
    { event: Event.e55, group: 3 },
    { event: Event.e55, group: 3 },
    {},
    {},
    { event: Event.e5b, group: 1 },
  ],
  [
    { event: Event.e55, group: 4 },
    { event: Event.e55, group: 4 },
    {},
    {},
    { event: Event.e5b, group: "1 / 2" },
  ],
  [
    { event: Event.e3o, group: 1 },
    { event: Event.e3o, group: 1 },
    {},
    {},
    { event: Event.e5b, group: 2 },
  ],
  [{ event: Event.e3o, group: 2 }, { event: Event.e3o, group: 2 }, {}, {}, {}],
  [
    { event: Event.e3o, group: 3 },
    { event: Event.e3o, group: 3 },
    { event: Event.e3o, group: 1 },
    {},
    {},
  ],
  [
    { event: Event.e3o, group: 4 },
    { event: Event.e3o, group: 4 },
    { event: Event.e3o, group: 2 },
    {},
    {},
  ],
  [
    { event: Event.e3o, group: 5 },
    { event: Event.e3o, group: 5 },
    { event: Event.e3o, group: 3 },
    { event: Event.e3o, group: 1 },
    {},
  ],
  [
    { event: Event.eme, round: 2 },
    { event: Event.eme, round: 2 },
    { event: Event.eme, round: 2 },
    { event: Event.eme, round: 2 },
    {},
  ],
  [
    { event: Event.e66, round: "Final" },
    { event: Event.e66, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.e77, round: "Final" },
    { event: Event.e77, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.e3b, round: 2 },
    { event: Event.e3b, round: 2 },
    { event: Event.e3b, round: 2 },
    { event: Event.e3b, round: 2 },
    {},
  ],
  [{}, {}, {}, {}, {}], // empty to end day

  // Saturday

  [
    { event: Event.e22, group: 1 },
    { event: Event.e22, group: 1 },
    {},
    {},
    { event: Event.e3f, attempt: 3 },
  ],
  [
    { event: Event.e22, group: 2 },
    { event: Event.e22, group: 2 },
    {},
    {},
    { event: Event.e3f, attempt: 3 },
  ],
  [
    { event: Event.e22, group: 3 },
    { event: Event.e22, group: 3 },
    {},
    {},
    { event: Event.e3f, attempt: 3 },
  ],
  [
    { event: Event.e22, group: 4 },
    { event: Event.e22, group: 4 },
    {},
    {},
    { event: Event.e3f, attempt: 3 },
  ],
  [
    { event: Event.e22, group: 5 },
    { event: Event.e22, group: 5 },
    {},
    {},
    { event: Event.e3f, attempt: 3 },
  ],
  [{ event: Event.e22, group: 6 }, { event: Event.e22, group: 6 }, {}, {}, {}],
  [{ event: Event.e22, group: 7 }, { event: Event.e22, group: 7 }, {}, {}, {}],
  [
    { event: Event.e22, group: 8 },
    { event: Event.e22, group: 8 },
    { event: Event.e22, group: 1 },
    {},
    {},
  ],
  [
    { event: Event.e22, group: 9 },
    { event: Event.e22, group: 9 },
    { event: Event.e22, group: 2 },
    {},
    {},
  ],
  [
    { event: Event.e22, group: 10 },
    { event: Event.e22, group: 10 },
    { event: Event.e22, group: 3 },
    { event: Event.e22, group: 1 },
    {},
  ],

  [{}, {}, {}, {}, {}], // lunch

  [
    { event: Event.e33, group: 1 },
    { event: Event.e33, group: 1 },
    { event: Event.e33, group: 1 },
    { event: Event.e33, group: 1 },
    {},
  ],
  [
    { event: Event.e33, group: 2 },
    { event: Event.e33, group: 2 },
    { event: Event.e33, group: 2 },
    { event: Event.e33, group: 2 },
    {},
  ],
  [
    { event: Event.e33, group: 3 },
    { event: Event.e33, group: 3 },
    { event: Event.e33, group: 3 },
    { event: Event.e33, group: 3 },
    {},
  ],
  [
    { event: Event.e33, group: 4 },
    { event: Event.e33, group: 4 },
    { event: Event.e33, group: 4 },
    { event: Event.e33, group: 4 },
    {},
  ],
  [
    { event: Event.e33, group: 5 },
    { event: Event.e33, group: 5 },
    { event: Event.e33, group: 5 },
    { event: Event.e33, group: 5 },
    {},
  ],
  [
    { event: Event.e33, group: 6 },
    { event: Event.e33, group: 6 },
    { event: Event.e33, group: 6 },
    { event: Event.e33, group: 6 },
    {},
  ],
  [
    { event: Event.e33, group: 7 },
    { event: Event.e33, group: 7 },
    { event: Event.e33, group: 7 },
    { event: Event.e33, group: 7 },
    {},
  ],
  [
    { event: Event.e33, group: 8 },
    { event: Event.e33, group: 8 },
    { event: Event.e33, group: 8 },
    { event: Event.e33, group: 8 },
    {},
  ],
  [{ event: Event.epy, group: 1 }, { event: Event.epy, group: 1 }, {}, {}, {}],
  [
    { event: Event.epy, group: 2 },
    { event: Event.epy, group: 2 },
    {},
    {},
    { event: Event.e3m, attempt: 2 },
  ],
  [
    { event: Event.epy, group: 3 },
    { event: Event.epy, group: 3 },
    {},
    {},
    { event: Event.e3m, attempt: 2 },
  ],
  [
    { event: Event.epy, group: 4 },
    { event: Event.epy, group: 4 },
    {},
    {},
    { event: Event.e3m, attempt: 2 },
  ],
  [
    { event: Event.epy, group: 5 },
    { event: Event.epy, group: 5 },
    {},
    {},
    { event: Event.e3m, attempt: 2 },
  ],
  [
    { event: Event.epy, group: 6 },
    { event: Event.epy, group: 6 },
    {},
    {},
    { event: Event.e3m, attempt: 2 },
  ],
  [{ event: Event.epy, group: 7 }, { event: Event.epy, group: 7 }, {}, {}, {}],
  [
    { event: Event.epy, group: 8 },
    { event: Event.esk, group: 1 },
    { event: Event.esk, group: 1 },
    { event: Event.esk, group: 1 },
    {},
  ],
  [
    { event: Event.epy, group: 9 },
    { event: Event.esk, group: 2 },
    { event: Event.esk, group: 2 },
    { event: Event.esk, group: 2 },
    {},
  ],
  [
    { event: Event.epy, group: 10 },
    { event: Event.esk, group: 3 },
    { event: Event.esk, group: 3 },
    { event: Event.esk, group: 3 },
    {},
  ],
  [
    { event: Event.epy, group: 11 },
    { event: Event.esk, group: 4 },
    { event: Event.esk, group: 4 },
    { event: Event.esk, group: 4 },
    {},
  ],
  [
    { event: Event.epy, group: 12 },
    { event: Event.esk, group: 5 },
    { event: Event.esk, group: 5 },
    {},
    {},
  ],
  [
    { event: Event.epy, group: 13 },
    { event: Event.esk, group: 6 },
    { event: Event.esk, group: 6 },
    {},
    {},
  ],
  [
    { event: Event.epy, group: 14 },
    { event: Event.esk, group: 7 },
    { event: Event.esk, group: 7 },
    {},
    {},
  ],

  [{}, {}, {}, {}, {}], // empty to end day

  // Sunday

  [
    { event: Event.e55, round: 2 },
    { event: Event.e55, round: 2 },
    { event: Event.e55, round: 2 },
    { event: Event.e55, round: 2 },
    {},
  ],
  [
    { event: Event.epy, round: 2 },
    { event: Event.epy, round: 2 },
    { event: Event.epy, round: 2 },
    { event: Event.epy, round: 2 },
    {},
  ],
  [
    { event: Event.esk, round: 2 },
    { event: Event.esk, round: 2 },
    { event: Event.esk, round: 2 },
    { event: Event.esk, round: 2 },
    {},
  ],
  [
    { event: Event.e33, round: 2, group: 1 },
    { event: Event.e33, round: 2, group: 1 },
    { event: Event.e33, round: 2, group: 1 },
    {},
    {},
  ],
  [
    { event: Event.e33, round: 2, group: 2 },
    { event: Event.e33, round: 2, group: 2 },
    { event: Event.e33, round: 2, group: 2 },
    {},
    { event: Event.e4b, group: 1 },
  ],
  [
    { event: Event.e33, round: 2, group: 3 },
    { event: Event.e33, round: 2, group: 3 },
    { event: Event.e33, round: 2, group: 3 },
    {},
    { event: Event.e4b, group: 1 },
  ],
  [
    { event: Event.e33, round: 2, group: 4 },
    { event: Event.e33, round: 2, group: 4 },
    { event: Event.e33, round: 2, group: 4 },
    {},
    { event: Event.e4b, group: 2 },
  ],
  [
    { event: Event.e33, round: 2, group: 5 },
    { event: Event.e33, round: 2, group: 5 },
    { event: Event.e33, round: 2, group: 5 },
    {},
    {},
  ],
  [
    { event: Event.e22, round: 2 },
    { event: Event.e22, round: 2 },
    { event: Event.e22, round: 2 },
    { event: Event.e22, round: 2 },
    {},
  ],
  [
    { event: Event.e3o, round: 2 },
    { event: Event.e3o, round: 2 },
    { event: Event.e3o, round: 2 },
    { event: Event.e3o, round: 2 },
    {},
  ],
  [
    { event: Event.e44, round: 2 },
    { event: Event.e44, round: 2 },
    { event: Event.e44, round: 2 },
    { event: Event.e44, round: 2 },
    {},
  ],
  [
    { event: Event.e33, round: 3 },
    { event: Event.e33, round: 3 },
    { event: Event.e33, round: 3 },
    { event: Event.e33, round: 3 },
    {},
  ],

  [{}, {}, {}, {}, {}], // lunch

  [
    { event: Event.esq, round: "Final" },
    { event: Event.esq, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.e3o, round: "Final" },
    { event: Event.e3o, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.eme, round: "Final" },
    { event: Event.eme, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.e55, round: "Final" },
    { event: Event.e55, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.epy, round: "Final" },
    { event: Event.epy, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.esk, round: "Final" },
    { event: Event.esk, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.e22, round: "Final" },
    { event: Event.e22, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.e44, round: "Final" },
    { event: Event.e44, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.e3b, round: "Final" },
    { event: Event.e3b, round: "Final" },
    {},
    {},
    {},
  ],
  [
    { event: Event.e33, round: "Final" },
    { event: Event.e33, round: "Final" },
    {},
    {},
    {},
  ],

  // !!!

  [{}, {}, {}, {}, {}], // empty to end day
];
